apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-backup-nguyen-thanh-son-staging
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 5Gi
    storageClassName: ceph-rbd
