version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 162001
      POSTGRES_DB: sowndev-strapi
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    # networks:
    #   - postgres
    expose:
      - 5432

  strapi:
    # image: strapi/strapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      DATABASE_NAME: sowndev-strapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 162001
    # volumes:
    #   - appstrapi:/srv/app
    ports:
      - "1337:1337"
    # depends_on:
    #   - database
    # networks:
    #   - postgres

# networks:
#   postgres:
#     driver: bridge

volumes:
    postgres:
    appstrapi: